---
# Run all tests
stages:
  - lint
  - deployment test

before_script:
  - rm -rf molecule/resources/provisioning
  - ansible --version
  - ansible-lint --version
  - molecule --version
  - git clone https://github.com/lean-delivery/ansible-molecule-drivers.git molecule/resources/provisioning

variables:
  GET_SOURCES_ATTEMPTS: "5"

Lint:
  stage: lint
  before_script:
    - git clone https://github.com/lean-delivery/ansible-lint-rules.git ~/ansible-lint-rules
  script:
    - yamllint . -c .yamllint
    - ansible-lint . -c .ansible-lint
  after_script:
    - rm -rf ~/ansible-lint-rules
  tags:
    - lint

.Docker ansible-beats:
  stage: deployment test
  script:
    - molecule test -s default
  tags:
    - aws

AWS ansible-beats:
  variables:
    AWS_REGION: us-east-1
  stage: deployment test
  script:
    - molecule test -s cloud-aws-direct
  tags:
    - aws

.AZURE ansible-beats:
  stage: deployment test
  script:
    - molecule test -s cloud-azure-direct
  tags:
    - azure
