---
# tasks file for beats

- name: check-parameters
  include_tasks: beats-param-check.yml

- name: os-specific vars
  include_vars: '{{ ansible_os_family }}.yml'

- name: Configure and install OS-specific packages
  include_tasks: '{{ beats_platform_tasks }}'
  with_first_found:
    - '{{ beats_tasks }}'
    - not-supported.yml
  loop_control:
    loop_var: beats_platform_tasks

- name: debug tasks
  debug:
    msg: 'beats-{{ ansible_os_family | lower }}-{{ beats_use_repository | string }}.yml'

- name: Install beats packages
  include_tasks: '{{ beats_pack_tasks }}'
  with_first_found:
    - 'beats-{{ ansible_os_family | lower }}-{{ beats_use_repository | string }}.yml'
    - beats-package.yml
  loop_control:
    loop_var: beats_pack_tasks

#Configuration file for beats
- name: Beats configuration
  include_tasks: beats-config.yml

- name: 'Start {{ beat }} service'
  service:
    name: '{{ beat }}'
    state: started
    enabled: true
  when: beats_start_service | bool
  register: beats_started
